### ISSUE TITLE
GmSSL-2.0在Linux上的编译问题

### ISSUE THREAD

**Issue by guanzhi** [guanzhi/GmSSL#398] opened 2017-12-08 12:38 UTC
所有GmSSL在Linux上的编译问题请回复此Issue，请勿开新主题

**Comment by Gabrielxinxin** [comment] 2017-12-10 08:39
Makefile:6658: recipe for target 'crypto/zuc/zuc.o' failed

**Comment by guanzhi** [comment] 2017-12-11 11:32
默认情况下ZUC已经被禁用了，这是在什么情况下出现的？

**Comment by Gabrielxinxin** [comment] 2017-12-11 15:50
enable-zuc

**Comment by guanzhi** [comment] 2017-12-13 10:37
不要用`enable-zuc`这个选项

**Comment by lilya3587** [comment] 2017-12-14 08:21
在linux上编译时： gcc GmSSL.c ../libssl.so ../libcrypto.so -I/usr/local/javajdk/jdk1.8.0_151/include -I/usr/local/javajdk/jdk1.8.0_151/include/linux  -fPIC -shared -o gmssl.so
出现错误![linuxgmssl](https://user-images.githubusercontent.com/31059946/33982027-0602fc3c-e0ea-11e7-855e-ac3a898f5729.jpg)

**Comment by guanzhi** [comment] 2017-12-18 09:22
可能是由于没有通过`-I`指定头文件所在路径导致的

**Comment by lilya3587** [comment] 2017-12-18 09:29
不知道怎么指定。。。我之前编译完了没有安装 就直接编译java的动态库（听别人说不用命令行可以不安装），结果出现上面的问题，后来我又从头开始弄，sudo make install 之后 再编译java的动态库gcc GmSSL.c ../libssl.so ../libcrypto.so -I/usr/local/javajdk/jdk1.8.0_151/include -I/usr/local/javajdk/jdk1.8.0_151/include/linux -fPIC -shared -o gmssl.so  就可以了

**Comment by lvmengkeji** [comment] 2017-12-23 08:55
刚取的master版本，在centos 6.5 x64编译：
./config
make

crypto/ffx/ffx.c:77: error: redefinition of typedef 'FFX_CTX'
include/openssl/ffx.h:78: note: previous declaration of 'FFX_CTX' was here
crypto/ffx/ffx.c: In function 'FFX_encrypt':
crypto/ffx/ffx.c:205: warning: dereferencing type-punned pointer will break strict-aliasing rules
crypto/ffx/ffx.c:218: warning: dereferencing type-punned pointer will break strict-aliasing rules
crypto/ffx/ffx.c: In function 'FFX_decrypt':
crypto/ffx/ffx.c:303: warning: dereferencing type-punned pointer will break strict-aliasing rules
crypto/ffx/ffx.c:317: warning: dereferencing type-punned pointer will break strict-aliasing rules
make[1]: *** [crypto/ffx/ffx.o] Error 1
make[1]: Leaving directory `/root/opensource/gmssl/GmSSL-master'
make: *** [all] Error 2

**Comment by guanzhi** [comment] 2017-12-26 02:33
你可以先用`./config no-ffx`禁用这个模块试试，稍后会修复

**Comment by SecureEngineer** [comment] 2018-01-05 01:03
make[2]: Entering directory /root/GmSSL-master' WARNING: mkdef.pl doesn't know the following algorithms: ASYNC Error: EVP_zuc does not have a number assigned LD_LIBRARY_PATH=: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib64/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -m64 -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive -ldl /usr/bin/ld:crypto.map:1: syntax error in VERSION script collect2: ld returned 1 exit status make[2]: *** [link_shlib.linux-shared] Error 1 make[2]: Leaving directory/root/GmSSL-master'
make[1]: *** [libcrypto.so] Error 2
make[1]: Leaving directory `/root/GmSSL-master'
make: *** [all] Error 2

**Comment by zhuanpan** [comment] 2018-01-09 09:26
在Linux上编译没有发现问题，但是gmssl version -a出现gmssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by SecureEngineer** [comment] 2018-01-09 10:40
需要你把/usr/local/lib64这个路径加入到/etc/ld.so.conf文件中，然后在终端中执行ldconfig指令，然后你再执行gmssl version -a ，神奇的一幕就出现啦。这个问题主要是在make install的时候没有将/usr/local/lib64的路径加入到系统搜索路径中造成。希望后续关老师可以解决这个问题。

**Comment by didiyou** [comment] 2018-04-16 08:53
install后没有提示错误，但是查看版本显示No such file or directory，运行gmssl显示 error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory，请问关老师为什么是这样？

**Comment by jishuo1213** [comment] 2018-05-04 13:05
ubuntu16.10上编译最新代码出现：
In function 'SDF_OpenDevice':
engines/sdf_dummy.c:209:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:209:10: note: each undeclared identifier is reported only once for each function it appears in
engines/sdf_dummy.c:212:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_CloseDevice':
engines/sdf_dummy.c:218:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_OpenSession':
engines/sdf_dummy.c:226:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:228:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;

这是config 命令 ./config no-saf no-sdf  no-skf no-sof no-zuc 
@guanzhi 关老师帮忙看下

**Comment by Hajime0** [comment] 2018-10-26 02:57
My OS is `Ubuntu 18.04.1 LTS` and I have an another official OpenSSL version 1.1.1 is installed.

I met the same issue as @jishuo1213 described when I was using `./config no-saf no-sdf no-skf no-sof no-zuc` to do the configuration. The issue is eventually resolved by following @ajeecai suggestion.

**Comment by zhaoxuyan** [comment] 2020-04-11 05:54
> install后没有提示错误，但是查看版本显示No such file or directory，运行gmssl显示 error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory，请问关老师为什么是这样？

ldconfig 一下

**Comment by mjjy** [comment] 2020-06-18 07:04
make 到中间位置卡住不动了
$sudo make
make depend && make _all
make[1]: Entering directory `/home/admin/gmssl'
make[1]: Leaving directory `/home/admin/gmssl'
make[1]: Entering directory `/home/admin/gmssl'
make -f ./Makefile.shared -e \
        PLATFORM=linux-x86_64 \
        PERL="/usr/bin/perl" SRCDIR='.' DSTDIR="." \
        INSTALLTOP='/usr/local/openssl' LIBDIR='lib' \
        LIBDEPS=' '""' -lz -ldl ' \
        LIBNAME=crypto LIBVERSION=1.1 \
        LIBCOMPATVERSIONS=';' \
        CC='gcc' CFLAGS='-DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/openssl\"" -DENGINESDIR="\"/usr/local/openssl/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE' \
        LDFLAGS='' \
        SHARED_LDFLAGS='-Wl,-znodelete -m64 ' SHLIB_EXT=.so.1.1 \
        RC='windres' SHARED_RCFLAGS='' \
        link_shlib.linux-shared
make[2]: Entering directory `/home/admin/gmssl'

**Comment by mjjy** [comment] 2020-06-18 10:53
老师，编译make 卡住不动，怎么解决呢？
ar: creating libssl.a
ranlib libssl.a || echo Never mind.
make -f ./Makefile.shared -e \
        PLATFORM=linux-x86_64 \
        PERL="/usr/bin/perl" SRCDIR='.' DSTDIR="." \
        INSTALLTOP='/usr/local/openssl' LIBDIR='lib' \
        LIBDEPS=' '""' -lz -ldl ' \
        LIBNAME=crypto LIBVERSION=1.1 \
        LIBCOMPATVERSIONS=';' \
        CC='gcc' CFLAGS='-DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/openssl\"" -DENGINESDIR="\"/usr/local/openssl/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE' \
        LDFLAGS='' \
        SHARED_LDFLAGS='-Wl,-znodelete -m64 ' SHLIB_EXT=.so.1.1 \
        RC='windres' SHARED_RCFLAGS='' \
        link_shlib.linux-shared
make[2]: Entering directory `/home/wb-fj502407/GmSSL'

**Comment by wonderffee** [comment] 2020-08-05 09:38
最新代码在Mac OS 10.15.5 上make报错
make[1]: *** No rule to make target `include/openssl/ffx.h', needed by `crypto/err/err_all.o'.  Stop

经查 include/openssl/ 文件夹下并无 ffx.h 文件

**Closed** 2020-12-27 01:12 UTC
Labels: no-issue-activity

**Comment by qianxiaoruxia-qoq** [comment] 2021-08-03 00:59
make[1]: *** [engines/sdf_dummy.o] Error 1
make[1]: Leaving directory `/home/GmSSL-gmbrowser-v0.1'
make: *** [all] 错误 2
老师，出现了这个问题怎么解？
